### ISSUE TITLE
Change Code Editor

### ISSUE THREAD

**Issue by overskul** [AkaruiDevelopment/panel#4]
Hi, the code editor in panel it's not good and don't have many features like back-step so why not change the code editor to embed editors like using Spck-Embed npm package or something else for more advanced features with coding and thanks

**Comment by Bumblebee-3** [comment]
Hey, thanks for the feedback. I will check out the package and then will consider changing it [if necessary].

-Blurr

**Comment by duckytutorials** [comment]
i will change it :D
- DuckeyDev

**Comment by Bumblebee-3** [comment]
@NezitX Have updated the code editor to Monaco Editor in [v0.0.5 release](https://github.com/AkaruiDevelopment/aoi.panel/releases/tag/0.0.5).
I'm closing this issue and marking it as resolved.
Thanks,
Bumblebee
